### ISSUE TITLE
Low power mode/custom refresh interval?

### ISSUE THREAD

**Issue by jonahclarsen** [BlueBubblesApp/bluebubbles-app#2820]
I've been using the Android app with direct connection (port forwarding/DDNS) and it's been working great (I could write a novel about the many way it's better then AirMessage).

However, the battery drain is bad - like 20%/day. I have it always running in the background (with the constant notification, and by locking it in Samsung's app switcher, and by disabling battery optimization). I do get notifications of new messages within 1-2s, which is great, but at too great a cost to battery life.

I'm wondering if there's any possibility of improving this - for example, if the "check with server" is what's causing most of the battery drain, maybe we could lower that interval to ~20s if there's been no messages in the past 30 minutes. It seems awfully wasteful of resources for it to be seemingly constantly connected and checking every second for messages when I only spend <5% of my day actually in an iMessage conversation. If it went into a low power state after ~30m of no messages where it would only be checking every 20-40s (maybe customizable values here), I would be completely happy with that, even if it only improved battery impact by 10% (but I imagine it would be even better).

Keep up the great work, thank you for the amazing app!

**Comment by tneotia** [comment]
I assume you are using our foreground service option for notifications? If so, the next app update includes a fully revamped background service that significantly improves battery drain. We have a beta available.

**Comment by zlshames** [comment]
Next update should help with battery drain. And the following update, even more. We found a small leak in the code and it's been fixed in the beta. And we have other optimizations we are working on on the side

**Comment by jonahclarsen** [comment]
Yes I'm using the foreground service. That's great to hear! Is there a place to get the beta apk now? I would be willing to test it out :)

**Comment by i-like-trains72** [comment]
Apologies for hijacking but you mentioned locking an app in Samsung's app switcher. What exactly is that/how do I access it? Is it available on Android 13? Been dealing with stupid samsung shenanigans on background usage. Disabled battery optimization and all that, but I still see apps getting killed when my screen is off (notably spotify and youtube music) or other odd behavior...

**Comment by jjoelj** [comment]
> Apologies for hijacking but you mentioned locking an app in Samsung's app switcher. What exactly is that/how do I access it? Is it available on Android 13? Been dealing with stupid samsung shenanigans on background usage. Disabled battery optimization and all that (did everything I found on DKMA), but I still see apps getting killed when my screen is off (notably spotify and youtube music) or other odd behavior...

https://www.samsung.com/us/support/answer/ANS10001359/#:~:text=To%20keep%20an%20app%20always,then%20select%20Stop%20keeping%20open.

**Comment by jjoelj** [comment]
> Yes I'm using the foreground service. That's great to hear! Is there a place to get the beta apk now? I would be willing to test it out :)

https://github.com/BlueBubblesApp/bluebubbles-app/releases/tag/v1.14.0%2B67-b.1

**Comment by jonahclarsen** [comment]
> > Apologies for hijacking but you mentioned locking an app in Samsung's app switcher. What exactly is that/how do I access it? Is it available on Android 13? Been dealing with stupid samsung shenanigans on background usage. Disabled battery optimization and all that (did everything I found on DKMA), but I still see apps getting killed when my screen is off (notably spotify and youtube music) or other odd behavior...
> 
> https://www.samsung.com/us/support/answer/ANS10001359/#:~:text=To%20keep%20an%20app%20always,then%20select%20Stop%20keeping%20open.

This is right, I just want to add - to get the menu that allows you to lock the app, you press and hold on the _app icon_ at the top of the app in the app switcher, _not_ on the app itself (if you do that, it triggers the app to go into pop-out mode). Took me a few minutes of confusion to get this.

**Comment by zlshames** [comment]
Battery drain should be MUCH better after the rewrite is released. You can test out the beta on the PlayStore or via GitHub. Closing this issue and if you still have battery issues, please re-open a ticket.
